### ISSUE TITLE
Linq 是自带分页的

### ISSUE THREAD

**Issue by duotai** [dotnetcore/Collections#3]
Linq 是自带分页的:

```
var query = list.AsQuaryable();
query = query.Skip(pageSize *(pageIndex  - 1)).Take(pageSize);
```

Collection Utilty 的作用不明显, 这点麻烦下作者做出详尽些的分享, 麻烦了.

**Comment by alexinea** [comment]
分页除了切出那一页的数据外，还需要获得一些别的东西（如一共多少页、当前第几页、后面还有没有页、每页有多少数据等等）以供分页组件使用。其实 Collections.Paginable 在处理 IQueryable 实例时便是如楼主所述来实现的（当然，还有性能方面的一些考量）

Collections.Paginable 没啥技术含量，api 使用起来很简单，Sample 项目和跑分项目中有 api 的使用方法。
